Repository knative-extensions/kn-plugin-event, pull requests merged in 2021-09, with the labels that each got.

#57 Auto updates/update community main
  OWNERS_ALIASES
Labels: cla: yes, kind/cleanup, approved, size/M, lgtm

#59 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/magefile/mage/LICENSE
  vendor/knative.dev/client/pkg/eventing/v1/client.go
  vendor/knative.dev/client/pkg/messaging/v1/channels_client.go
  vendor/knative.dev/client/pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/client/pkg/util/unstructured.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#62 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#60 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/S
