Repository knative-extensions/kn-plugin-event, pull requests merged in 2021-10, with the labels that each got.

#65 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, size/M, lgtm

#70 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: cla: yes, approved, size/XS, lgtm

#92 :broom: Replacing github.com/stretchr/testify with gotest.tools/v3
  cmd/kn-event-sender/main_test.go
  cmd/kn-event/cmd/build_test.go
  cmd/kn-event/cmd/root_test.go
  cmd/kn-event/cmd/send_test.go
  cmd/kn-event/cmd/version_test.go
  cmd/kn-event/main_test.go
  go.mod
  pkg/cli/create_test.go
  pkg/cli/ics/encoding_test.go
  pkg/cli/ics/send_test.go
  pkg/cli/send_test.go
  pkg/event/create_test.go
  pkg/event/sender_test.go
  pkg/sender/in_cluster_test.go
  pkg/tests/delta.go
  vendor/modules.txt
Labels: cla: yes, kind/cleanup, approved, size/L, lgtm

#89 :gift: kn-event registered as internal plugin
  cmd/kn-event/main.go
  cmd/kn-event/main_test.go
  internal/cli/cmd/build.go
  internal/cli/cmd/build_test.go
  internal/cli/cmd/builder.go
  internal/cli/cmd/root.go
  internal/cli/cmd/root_test.go
  internal/cli/cmd/send.go
  internal/cli/cmd/send_test.go
  internal/cli/cmd/testing.go
  internal/cli/cmd/types.go
  internal/cli/cmd/version.go
  internal/cli/cmd/version_test.go
  pkg/metadata/names.go
  pkg/metadata/plugin_name.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/testing.go
  third_party/VENDOR-LICENSE/github.com/mitchellh/go-homedir/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/client/pkg/LICENSE
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/knative.dev/client/pkg/kn/plugin/stat.go
  vendor/knative.dev/client/pkg/kn/plugin/stat_windows.go
  vendor/knative.dev/client/pkg/kn/plugin/verify.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, approved, kind/enhancement, lgtm
