Repository knative-extensions/kn-plugin-event, pull requests merged in 2021-03, with the labels that each got.

#2 Update module name to knative.dev/kn-plugin-event
  .gitignore
  Magefile.go
  cmd/kn-event-sender/main.go
  cmd/kn-event-sender/main_test.go
  cmd/kn-event/cmd/build.go
  cmd/kn-event/cmd/build_test.go
  cmd/kn-event/cmd/builder.go
  cmd/kn-event/cmd/root.go
  cmd/kn-event/cmd/send.go
  cmd/kn-event/cmd/send_test.go
  cmd/kn-event/cmd/version.go
  cmd/kn-event/cmd/version_test.go
  cmd/kn-event/main.go
  cmd/kn-event/main_test.go
  go.mod
  internal/cli/create.go
  internal/cli/create_test.go
  internal/cli/ics/encoding_test.go
  internal/cli/ics/send.go
  internal/cli/ics/send_test.go
  internal/cli/ics/types.go
  internal/cli/options.go
  internal/cli/retcode/retcode_test.go
  internal/cli/send_test.go
  internal/cli/target.go
  internal/cli/target_test.go
  internal/cli/types.go
  internal/configuration/cli.go
  internal/configuration/defaults.go
  internal/configuration/ics.go
  internal/event/constants.go
  internal/event/create_test.go
  internal/event/sender_test.go
  internal/k8s/addressresolver_test.go
  internal/k8s/kubeclient.go
  internal/sender/create.go
  internal/sender/direct_test.go
  internal/sender/in_cluster.go
  internal/sender/in_cluster_test.go
  internal/sender/types.go
  mage.go
Labels: cla: yes, lgtm, size/L

#3 Update README
  README.adoc
  README.md
Labels: cla: yes, lgtm, size/M

#4 [Automated] Format markdown
  README.md
Labels: cla: yes, lgtm, size/S
