Repository knative-extensions/kn-plugin-event, pull requests merged in 2021-07, with the labels that each got.

#35 Fixing golangci-lint errors across code base
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  .gitignore
  .golangci.yaml
  Magefile.go
  cmd/kn-event/cmd/build.go
  cmd/kn-event/cmd/build_test.go
  cmd/kn-event/cmd/builder.go
  cmd/kn-event/cmd/root.go
  cmd/kn-event/cmd/root_test.go
  cmd/kn-event/cmd/send.go
  cmd/kn-event/cmd/send_test.go
  cmd/kn-event/cmd/testing.go
  cmd/kn-event/cmd/types.go
  cmd/kn-event/cmd/version.go
  cmd/kn-event/cmd/version_test.go
  cmd/kn-event/main.go
  cmd/kn-event/main_test.go
  internal/cli/create.go
  internal/cli/create_test.go
  internal/cli/ics/send.go
  internal/cli/ics/types.go
  internal/cli/options.go
  internal/cli/retcode/retcode_test.go
  internal/cli/send.go
  internal/cli/send_test.go
  internal/cli/types.go
  internal/cli/version.go
  internal/event/create.go
  internal/event/create_test.go
  internal/event/sender.go
  internal/event/types.go
  internal/k8s/jobrunner.go
  internal/sender/create.go
  internal/sender/direct.go
  internal/sender/direct_test.go
  internal/sender/in_cluster.go
  internal/sender/in_cluster_test.go
  internal/sender/types.go
  internal/tests/cloudevent_server.go
  internal/tests/cloudevents_data.go
Labels: approved, cla: yes, lgtm, size/XL

#23 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#39 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#40 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#42 Fixing the jobrunner
  pkg/k8s/addressresolver_test.go
  pkg/k8s/errors.go
  pkg/k8s/jobrunner.go
  pkg/k8s/jobrunner_test.go
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#47 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#46 Autofill namespaces from kube config
  cmd/kn-event/cmd/send.go
  pkg/cli/send.go
  pkg/cli/send_test.go
  pkg/cli/target.go
  pkg/configuration/defaults.go
  pkg/configuration/memoized.go
  pkg/configuration/memoized_test.go
  pkg/event/types.go
  pkg/k8s/kubeclient.go
  pkg/sender/namespace.go
  pkg/tests/fakeclients.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#48 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#49 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/README.md
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/conversion_error.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#50 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/serving/config_changes.go
  vendor/knative.dev/client/pkg/serving/revision_template.go
  vendor/knative.dev/client/pkg/serving/v1/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
