Repository knative-extensions/kn-plugin-event, pull requests merged in 2021-11, with the labels that each got.

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/errors/errors.go
  vendor/knative.dev/client/pkg/errors/factory.go
  vendor/knative.dev/client/pkg/kn/config/config.go
  vendor/knative.dev/client/pkg/kn/flags/podspec.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#102 :bug: Ignore ireturn, and varnamelen linters
  .github/workflows/golangci-lint.yml
  .github/workflows/knative-style.yaml
  .golangci.yaml
Labels: cla: yes, approved, kind/bug, lgtm, size/S

#101 :bug: Configure git remote in case the source isn't checkout from origin
  Magefile.go
Labels: cla: yes, approved, kind/bug, lgtm, size/S

#96 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#95 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#104 :broom: Display maturity level as ALPHA using shields.io
  README.md
Labels: cla: yes, kind/cleanup, approved, size/XS, lgtm

#99 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, size/M, lgtm

#105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#106 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#107 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#108 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#112 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: cla: yes, approved, size/L, lgtm

#114 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm
