Repository knative-extensions/kn-plugin-event, pull requests merged in 2022-02, with the labels that each got.

#155 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#156 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#157 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#159 :gift: Tests for Eventing (Broker & Channel)
  pkg/tests/logging/context.go
  pkg/tests/logging/json.go
  pkg/tests/logging/logger.go
  pkg/tests/logging/reconciler.go
  pkg/tests/reference/core.go
  pkg/tests/reference/core_test.go
  pkg/tests/reference/eventing.go
  pkg/tests/reference/eventing_test.go
  pkg/tests/reference/gvk.go
  pkg/tests/reference/kref.go
  pkg/tests/reference/serving.go
  pkg/tests/reference/serving_test.go
  pkg/tests/reference/utils_test.go
  test/e2e/broker.go
  test/e2e/channel.go
  test/e2e/ics_send.go
  test/e2e/ics_send_test.go
  test/e2e/k8s_service.go
  test/e2e/kn_service.go
  test/e2e/logging.go
  test/e2e/main_test.go
  test/e2e/sut.go
Labels: approved, kind/enhancement, lgtm, size/XL

#161 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#162 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, size/M, lgtm
