Repository knative-extensions/kn-plugin-event, pull requests merged in 2022-04, with the labels that each got.

#170 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#175 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#176 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#173 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, size/XS, lgtm

#182 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#183 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
