Repository knative-extensions/kn-plugin-event, pull requests merged in 2022-01, with the labels that each got.

#136 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#139 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#141 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#146 :bug: Always send to cluster local Ksvc, when using in-cluster-sender
  pkg/k8s/addressresolver.go
  pkg/k8s/addressresolver_test.go
Labels: approved, kind/bug, size/M, lgtm

#147 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#151 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#152 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#153 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm
