Repository knative-extensions/kn-plugin-event, pull requests merged in 2022-03, with the labels that each got.

#168 Allow to override the test image resolver, to use env variables.
  go.mod
  test/e2e-tests.sh
  test/e2e/ics_send_test.go
  test/e2e/images.go
  test/e2e/kn_service.go
  test/images/envbased.go
  test/images/register.go
  test/images/resolver.go
  test/pkg/clients.go
  test/pkg/k8s/addressresolver_test.go
  vendor/gotest.tools/v3/poll/check.go
  vendor/gotest.tools/v3/poll/poll.go
  vendor/modules.txt
Labels: approved, kind/enhancement, size/L, lgtm

#165 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#144 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, size/M, lgtm

#169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm
