Repository knative-extensions/kn-plugin-event, pull requests merged in 2022-10, with the labels that each got.

#226 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#227 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#230 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#233 :bug: Align artifact.list location
  hack/release.sh
Labels: approved, size/XS, kind/bug, lgtm

#237 :broom: Align deps with 1.8 release
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/cleanup, approved, lgtm, size/S

#238 [release-1.8] :broom: Align deps with 1.8 release
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#241 :bug: Delete successful job with background propagation policy
  go.mod
  pkg/k8s/jobrunner.go
  test/e2e/ics_send.go
Labels: approved, kind/bug, lgtm, size/S

#240 :bug: RFC 1123 valid sender job name
  internal/cli/cmd/root.go
  pkg/sender/in_cluster.go
  pkg/sender/in_cluster_test.go
  test/e2e/ics_send.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: approved, kind/bug, size/L, lgtm
