Repository knative-extensions/kn-plugin-event, pull requests merged in 2023-02, with the labels that each got.

#265 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#266 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#267 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#270 Fix broken checksums generation
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#269 [release-1.9] :bug: Bumping knative.dev/hack to latest main
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, kind/bug, size/L, lgtm
