Repository knative-extensions/kn-plugin-event, pull requests merged in 2024-11, with the labels that each got.

#386 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#385 [release-1.15] :bug: Use patch level version in go.mod files
  build/go.mod
  go.mod
  go.work
Labels: approved, size/XS, kind/bug, lgtm

#387 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
