Repository knative-extensions/kn-plugin-event, pull requests merged in 2024-10, with the labels that each got.

#370 :book: Event sending docs with --to option acting as a sink
  README.md
Labels: kind/documentation, approved, size/M, lgtm

#363 [main] Upgrade to latest dependencies
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: approved, size/L, lgtm

#372 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#374 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#371 [main] Upgrade to latest dependencies
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: approved, size/L, lgtm

#376 [main] Upgrade to latest dependencies
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: approved, size/M, lgtm

#377 [main] Upgrade to latest dependencies
  go.work.sum
Labels: approved, size/M, lgtm

#379 :bug: Reset KUBERNETES env variables to ensure there's no Kube connection for unit test
  pkg/k8s/kubeclient_test.go
Labels: approved, kind/bug, lgtm, size/S

#380 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
