Repository knative-extensions/kn-plugin-event, pull requests merged in 2024-04, with the labels that each got.

#343 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#319 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#342 [main] Upgrade to latest dependencies
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: size/XXL, approved, lgtm

#345 :broom: Use knative.dev/toolbox/magetasks
  build/Magefile.go
  build/go.mod
  build/go.sum
  build/mage.go
  build/overrides/empty.go
  go.mod
  go.sum
  go.work.sum
Labels: kind/cleanup, approved, lgtm, size/XL

#346 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#344 [main] Upgrade to latest dependencies
  build/go.mod
  build/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: approved, lgtm, size/XL

#348 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#349 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
